#!/usr/bin/env python3
"""Inject Quick Answer (AEO/AIEO) + strong CTA into the 30 original blog posts.
Idempotent: skips posts that already contain the markers."""
import os, re, pathlib

BLOG_DIR = pathlib.Path(__file__).parent.parent / 'public' / 'blog'

# Slugs generated by gen-blogs.py (new posts) — skip, they already have everything
NEW_SLUGS = set()
gen_py = (pathlib.Path(__file__).parent / 'gen-blogs.py').read_text(encoding='utf-8')
for m in re.finditer(r'add\("[a-z]+",\s*"([a-z0-9-]+)"', gen_py):
    NEW_SLUGS.add(m.group(1))

QUICK_ANSWER_MARKER = '<!-- quick-answer-v1 -->'
CTA_MARKER = '<!-- strong-cta-v1 -->'

CTA_BLOCK = '''
          <!-- strong-cta-v1 -->
          <div class="glow-divider" style="margin:2rem 0;"></div>
          <section class="cta-block" style="margin-top:2.2rem;padding:2rem 1.8rem;background:linear-gradient(135deg,rgba(15,193,183,0.18),rgba(42,53,75,0.25));border:1px solid rgba(15,193,183,0.35);border-radius:16px;text-align:center;">
            <h2 style="color:var(--clr-text);margin-top:0;font-size:1.5rem;">Build Systems, Not Experiments</h2>
            <p style="color:var(--clr-text);margin:0.6rem 0 1.3rem;">AIM Tech AI designs and ships AI, cloud, and custom software systems for companies ready to turn technology into real business advantage.</p>
            <a href="/book" style="display:inline-block;padding:0.95rem 2rem;background:var(--clr-primary);color:#0a0608;border-radius:12px;font-weight:700;text-decoration:none;text-shadow:none;letter-spacing:0.3px;">Book a Strategy Call &rarr;</a>
            <div style="margin-top:0.9rem;font-size:0.82rem;color:var(--clr-text-dim);">Free 30-min consultation &bull; No obligation</div>
          </section>
'''

def derive_quick_answer(html):
    """Pull first meaningful <p> as the quick answer."""
    m = re.search(r'<article[^>]*>\s*(.*?)</article>', html, flags=re.DOTALL)
    if not m:
        return None
    body = m.group(1)
    pm = re.search(r'<p[^>]*>(.*?)</p>', body, flags=re.DOTALL)
    if not pm:
        return None
    txt = re.sub(r'<[^>]+>', '', pm.group(1)).strip()
    parts = re.split(r'(?<=[.!?])\s+', txt)
    qa = ' '.join(parts[:2]).strip()
    if len(qa) > 280:
        qa = qa[:277].rstrip() + '...'
    return qa

def inject(html):
    changes = []

    # 1) Quick Answer — insert before first <p> inside <article>
    if QUICK_ANSWER_MARKER not in html:
        qa = derive_quick_answer(html)
        if qa:
            qa_html = (
                f'          <!-- quick-answer-v1 -->\n'
                f'          <aside class="quick-answer" style="background:rgba(15,193,183,0.08);border-left:4px solid var(--clr-primary);border-radius:12px;padding:1.4rem 1.6rem;margin-bottom:1.8rem;">\n'
                f'            <div style="font-family:var(--font-mono);font-size:0.7rem;letter-spacing:3px;text-transform:uppercase;color:var(--clr-primary);margin-bottom:0.6rem;text-shadow:none;">Quick Answer</div>\n'
                f'            <p class="speakable-intro" style="margin:0;color:var(--clr-text);">{qa}</p>\n'
                f'          </aside>\n\n'
            )
            # Find first <p ...> inside first <article>
            new_html, n = re.subn(
                r'(<article[^>]*>\s*)(<p)',
                lambda m: m.group(1) + qa_html + '          ' + m.group(2),
                html, count=1, flags=re.DOTALL
            )
            if n:
                html = new_html
                changes.append('quick-answer')

    # 2) Strong CTA — insert before closing </article>
    if CTA_MARKER not in html:
        new_html, n = re.subn(
            r'(</article>)',
            CTA_BLOCK + r'\1',
            html, count=1
        )
        if n:
            html = new_html
            changes.append('cta')

    return html, changes

def main():
    upgraded = []
    for f in sorted(BLOG_DIR.glob('*.html')):
        slug = f.stem
        if slug in NEW_SLUGS:
            continue  # new posts already have these built in
        html = f.read_text(encoding='utf-8')
        new_html, changes = inject(html)
        if changes:
            f.write_text(new_html, encoding='utf-8')
            upgraded.append((slug, changes))
    for s, c in upgraded:
        print(f'upgraded {s}: {",".join(c)}')
    print(f'\ntotal upgraded: {len(upgraded)}')

if __name__ == '__main__':
    main()
